FROM openjdk:21-jdk-slim-buster AS build
WORKDIR /app

COPY pom.xml .
COPY .mvn .mvn
COPY mvnw .
RUN ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
COPY src src

RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine-3.22

WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]

# CMD ["java", "-jar", "/app/app.jar", "--logging.level.org.springframework=DEBUG"]
