CREATE SCHEMA IF NOT EXISTS cinema;

CREATE TABLE IF NOT EXISTS cinema.movie_cast
(
    movie_id    BIGINT NOT NULL,
    cast_member VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cinema.movie_genres
(
    movie_id BIGINT NOT NULL,
    genres   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cinema.movie_writers
(
    movie_id BIGINT NOT NULL,
    writers  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cinema.movies
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    year                INTEGER                                 NOT NULL,
    description         TEXT,
    rating              INTEGER                                 NOT NULL,
    duration_in_minutes INTEGER                                 NOT NULL,
    director            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

ALTER TABLE cinema.movie_cast
    DROP CONSTRAINT IF EXISTS fk_movie_cast_on_movie;

ALTER TABLE cinema.movie_cast
    ADD CONSTRAINT fk_movie_cast_on_movie FOREIGN KEY (movie_id) REFERENCES cinema.movies (id);

ALTER TABLE cinema.movie_genres
    DROP CONSTRAINT IF EXISTS fk_movie_genres_on_movie;

ALTER TABLE cinema.movie_genres
    ADD CONSTRAINT fk_movie_genres_on_movie FOREIGN KEY (movie_id) REFERENCES cinema.movies (id);

ALTER TABLE cinema.movie_writers
    DROP CONSTRAINT IF EXISTS fk_movie_writers_on_movie;

ALTER TABLE cinema.movie_writers
    ADD CONSTRAINT fk_movie_writers_on_movie FOREIGN KEY (movie_id) REFERENCES cinema.movies (id);
