CREATE TABLE movie_cast
(
  movie_id    BIGINT NOT NULL,
  cast_member VARCHAR(255)
);

CREATE TABLE movie_genres
(
  movie_id BIGINT NOT NULL,
  genres   VARCHAR(255)
);

CREATE TABLE movie_writers
(
  movie_id BIGINT NOT NULL,
  writers  VARCHAR(255)
);

CREATE TABLE movies
(
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title               VARCHAR(255)                            NOT NULL,
  year                INTEGER                                 NOT NULL,
  description         TEXT,
  rating              INTEGER                                 NOT NULL,
  duration_in_minutes INTEGER                                 NOT NULL,
  director            VARCHAR(255)                            NOT NULL,
  CONSTRAINT pk_movies PRIMARY KEY (id)
);

ALTER TABLE movie_cast
  ADD CONSTRAINT fk_movie_cast_on_movie FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE movie_genres
  ADD CONSTRAINT fk_movie_genres_on_movie FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE movie_writers
  ADD CONSTRAINT fk_movie_writers_on_movie FOREIGN KEY (movie_id) REFERENCES movies (id);