CREATE TABLE cinema.rooms
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(50)                             NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE'            NOT NULL,
    rows   JSONB,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE cinema.sessions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_id   BIGINT                                  NOT NULL,
    room_id    BIGINT                                  NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE                NOT NULL,
    end_time   TIMESTAMP WITH TIME ZONE                NOT NULL,
    status     VARCHAR(20) DEFAULT 'SCHEDULED'         NOT NULL,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

CREATE TABLE cinema.tickets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     UUID                                    NOT NULL,
    session_id  BIGINT                                  NOT NULL,
    seat_number VARCHAR(3)                              NOT NULL,
    status      VARCHAR(20) DEFAULT 'BOOKED'            NOT NULL,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

ALTER TABLE cinema.rooms
    ADD CONSTRAINT uc_rooms_name UNIQUE (name);

ALTER TABLE cinema.tickets
    ADD CONSTRAINT uk_unique_session_seat UNIQUE (session_id, seat_number);

ALTER TABLE cinema.sessions
    ADD CONSTRAINT FK_SESSIONS_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES cinema.movies (id);

ALTER TABLE cinema.sessions
    ADD CONSTRAINT FK_SESSIONS_ON_ROOM FOREIGN KEY (room_id) REFERENCES cinema.rooms (id);

DROP INDEX IF EXISTS idx_active_sessions;
CREATE INDEX idx_active_sessions ON cinema.sessions (room_id) WHERE status = 'SCHEDULED';

ALTER TABLE cinema.tickets
    ADD CONSTRAINT FK_TICKETS_ON_SESSION FOREIGN KEY (session_id) REFERENCES cinema.sessions (id);

ALTER TABLE cinema.tickets
    ADD CONSTRAINT FK_TICKETS_ON_USER FOREIGN KEY (user_id) REFERENCES auth.users (id);
