CREATE TABLE cinema.movie_credits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_id  BIGINT                                  NOT NULL,
    person_id UUID                                    NOT NULL,
    role      VARCHAR                                 NOT NULL,
    CONSTRAINT pk_movie_credits PRIMARY KEY (id)
);

ALTER TABLE cinema.movie_credits
    ADD CONSTRAINT FK_MOVIE_CREDITS_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES cinema.movies (id);

ALTER TABLE cinema.movie_credits
    ADD CONSTRAINT FK_MOVIE_CREDITS_ON_PERSON FOREIGN KEY (person_id) REFERENCES cinema.persons (id);
