CREATE TABLE IF NOT EXISTS cinema.genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

ALTER TABLE cinema.movie_genres
    RENAME COLUMN genres TO genre_id;

ALTER TABLE cinema.movie_genres
    ALTER COLUMN genre_id SET DATA TYPE BIGINT USING genre_id::BIGINT;

ALTER TABLE cinema.movies
    DROP COLUMN IF EXISTS genre;

ALTER TABLE cinema.genres
    ADD CONSTRAINT uc_genres_name UNIQUE (name);

ALTER TABLE cinema.movie_genres
    ADD CONSTRAINT fk_movgen_on_genre FOREIGN KEY (genre_id) REFERENCES cinema.genres (id);

ALTER TABLE cinema.movie_genres
    ADD CONSTRAINT fk_movgen_on_movie FOREIGN KEY (movie_id) REFERENCES cinema.movies (id);
